// packages/react/src/jsx-runtime.ts
import {
  createJsxElement,
  cs,
  type Client,
  type JsxElementOf,
  type JsxElementTypeOf,
  type Spliceable,
} from "@backtickjs/core";
import type { JSX as React, ReactElement, ReactNode } from "react";
import { createElement, Fragment as ReactFragment } from "./index.js";

// JSX as React types it, for a host's JSX and a script's alike: an element is
// also a client value, so a host hands one over, and a tag may also name a
// server component, which answers a script.
export declare namespace JSX {
  export type Element = JsxElementOf<React.Element>;
  export type ElementType = JsxElementTypeOf<ReactNode> | React.ElementType;
  export type ElementClass = React.ElementClass;
  export type ElementAttributesProperty = React.ElementAttributesProperty;
  export type ElementChildrenAttribute = React.ElementChildrenAttribute;
  export type LibraryManagedAttributes<C, P> = React.LibraryManagedAttributes<
    C,
    P
  >;
  export type IntrinsicAttributes = React.IntrinsicAttributes;
  export type IntrinsicClassAttributes<T> = React.IntrinsicClassAttributes<T>;
  export type IntrinsicElements = React.IntrinsicElements;
}

/**
 * `<>` and `<Fragment>` on the host: its children as React's fragment's, each
 * an argument rather than an array, so React asks none of them for a key.
 */
export function Fragment(props: {
  children?: Spliceable;
}): Client<ReactElement> {
  const children: readonly Spliceable[] =
    props.children === undefined
      ? []
      : Array.isArray(props.children)
        ? props.children
        : [props.children];
  return cs`$createElement(
    $ReactFragment,
    null,
    ...($children as ReactNode[]),
  )`;
}

// A server component's element: expanded on the host when a bundle is built,
// what it answers standing where it stood. Hooks belong to client components,
// as in React: a server component's output is a node, never rendered as one.
// Its `key`, which the JSX transform passes apart from the props, keys a
// fragment around that node, so React can tell a list's entries apart.
export function jsx(
  type: JSX.ElementType,
  props: unknown,
  key?: string | number,
): JSX.Element {
  // Core's element, as this adapter types it: a stand-in for a React element.
  const element = createJsxElement(
    type as (props: never) => unknown,
    props,
  ) as unknown as JSX.Element;
  if (key === undefined) {
    return element;
  }
  return cs`$createElement(
    $ReactFragment,
    { key: $key },
    $element,
  )` as JSX.Element;
}

export const jsxs = jsx;
// What a development build of the JSX transform calls, as Bun does.
export const jsxDEV = jsx;

// packages/solid-js/src/jsx-runtime.ts
import { createJsxElement } from "@backtickjs/core";
import type { BacktickElement, Spliceable } from "@backtickjs/core";
import type { JSX as Solid } from "solid-js";

// What the JSX transform reaches for in a file drawn with this adapter, and
// what TypeScript reads a tag through: Solid's elements, each attribute a
// `Prop` — host data, or a script standing for it — so what a script hands an
// element is checked the way a host's is.

/**
 * Children with no element of their own: `<>` and `<Fragment>`. Solid has no
 * component for it — its compiler writes a fragment as an array — so this is a
 * server component whose drawing is that array. Always an array, so a single
 * child that is a script stays a child, read where it stands, rather than a
 * script the component drew.
 */
export function Fragment(props: { children?: Prop<JSX.Element> }): JSX.Element {
  // What JSX types a drawing as; the bundler writes the array as it is.
  return [props.children] as unknown as JSX.Element;
}

/**
 * What a prop admits: what the server wrote, or a script standing in for it. A
 * function has no written form — client behaviour is `cs`...` — so a handler
 * prop is left with the script arm alone.
 */
export type Prop<T> = Spliceable<T>;

// An element's props as Solid types them, each a `Prop`, and its children.
type Props<Attributes> = {
  [Key in keyof Attributes as Key extends "children" ? never : Key]?: Prop<
    Exclude<Attributes[Key], undefined>
  >;
} & { children?: Prop<JSX.Element> };

type Elements = {
  [Tag in keyof Solid.IntrinsicElements]: Props<Solid.IntrinsicElements[Tag]>;
};

export declare namespace JSX {
  /** Solid's `JSX.Element`, with a `BacktickElement` where Solid has a `Node`. */
  export type Element =
    | BacktickElement
    | ArrayElement
    | (string & {})
    | number
    | boolean
    | null
    | undefined;
  export interface ArrayElement extends Array<Element> {}
  export interface IntrinsicElements extends Elements {}
  /** A tag: an element to draw, or a component that answers a drawing. */
  export type ElementType =
    | string
    | ((props: never) => Prop<Element>)
    | ((props: never) => Promise<Prop<Element>>);
  export interface ElementChildrenAttribute {
    children: unknown;
  }
}

export function jsx(type: JSX.ElementType, props: unknown): JSX.Element {
  return createJsxElement(type, props);
}

export const jsxs = jsx;
// What a development build of the JSX transform calls, as Bun does.
export const jsxDEV = jsx;
